fullname: Inquisitive Logic
shortname: inquisitive-logic
branch: main
opam_name: coq-inqlog
organization: motrellin

travis: false
action: true
circlecli: false
nix: false
ci_test_dependants: false
ci_extra_dev: false
#action_appendix:

community: false
coqdoc: true
submodule: true #At least for coqdocjs

dune: false

#doi:
synopsis: A Formalization of Inquisitive Logic
description: |
  A formalization of inquisitive logic in Rocq, based on the work of e.g. [Ivano Ciardelli](doi.org/10.1007/978-3-031-09706-5).

#chat:

authors:
  - name: Max Ole Elliger
    initial: true
    email: ole.elliger@fau.de
#after_authors:
maintainers:
  - name: Max Ole Elliger
    nickname: motrellin

#license: TODO
  #fullname: GNU General Public License v3.0 or later
  #identifier: GPL-3.0-or-later

supported_coq_versions:
  text: Developed for 9.0
  opam: '{ "9.0" }'

#supported_ocaml_versions:

dependencies:
  - description: Autosubst
    opam:
      name: coq-autosubst

#categories:
#keywords:
#date:

namespace: InqLog

#publications:

#build:
make_target: all
#test_target:
#install_flag:
#extracted:

#TODO
documentation: |-
  ## Documentation

  This project tries to formalize inquisitive logic in Rocq. The formalization
  is based on the work of e.g. [Ivano Ciardelli](doi.org/10.1007/978-3-031-09706-5).

  ### Contributing

  You can find information on how to contribute in the [CONTRIBUTING.md](.github/CONTRIBUTING.md) file.

#TODO
#index_documentation:

coqdoc_index: ./html/toc.html

opam-file-maintainer: ole.elliger@fau.de
#opam-file-version:

#tested_coq_nix_versions:
#tested_coq_opam_versions:
tested_rocq_opam_versions:
  - version: '9.0'
    #repo: 'rocq/rocq-prover'

#ci_cron_schedule:
#cachix:
#circleci_after_script:
