fullname: Inquisitive Logic
shortname: inquisitive-logic
branch: main
opam_name: coq-inqlog
organization: motrellin

travis: false
action: true
circlecli: false
nix: false
ci_test_dependants: false
ci_extra_dev: false
#action_appendix:

community: false
coqdoc: true
submodule: true #At least for coqdocjs

dune: false

#doi:
synopsis: A Formalization of Inquisitive Logic
description: |
  This project formalizes inquisitive logic in Rocq, based on the work of e.g. [Ivano Ciardelli](doi.org/10.1007/978-3-031-09706-5).
  The current focus lies on (bounded) inquisitive first-order logic, therefore providing a formalization of the basic syntax (using arity types), support and truth semantics, followed by the formalization of a sequent calculus by Litak/Sano whose corresponding paper (Bounded inquistive logics: Sequent calculi and schematic validity) got accepted for [TABLEAUX 2025](https://icetcs.github.io/frocos-itp-tableaux25/tableaux/).
  The theory is located under `theories/`.
  Some concrete instances of type classes (e.g. signatures) are located under `instances/`.
  We also provide some examples (`examples/`) in order to demonstrate the implemented theory.

#chat:

authors:
  - name: Max Ole Elliger
    initial: true
    email: ole.elliger@fau.de
#after_authors:
maintainers:
  - name: Max Ole Elliger
    nickname: motrellin

license:
  fullname: 'BSD 3-Clause "New" or "Revised" License'
  identifier: BSD-3-Clause

supported_coq_versions:
  text: Developed for 9.0
  opam: '{ "9.0" }'

#supported_ocaml_versions:

dependencies:
  - description: Autosubst
    opam:
      name: coq-autosubst

#categories:
#keywords:
#date:

namespace: InqLog

publications:
  - pub_title: "Inquisitive Logic: Consequence and Inference in the Realm of Questions"
    pub_url: "https://link.springer.com/book/10.1007/978-3-031-09706-5"
    pub_doi: "10.1007/978-3-031-09706-5"
  - pub_title: "Coherence in inquisitive first-order logic"
    pub_url: "https://www.sciencedirect.com/science/article/pii/S0168007222000707"
    pub_doi: "10.1016/j.apal.2022.103155"
  - pub_title: "Bounded inquisitive logic: Sequent calculi and schematic validity"
    pub_url: "https://icetcs.github.io/frocos-itp-tableaux25/tableaux/"

#build:
make_target: all
#test_target:
#install_flag:
#extracted:

documentation: |-
  ## Documentation

  This project formalizes inquisitive logic in Rocq, based on the work of e.g. [Ivano Ciardelli](doi.org/10.1007/978-3-031-09706-5).
  The current focus lies on (bounded) inquisitive first-order logic, therefore providing a formalization of the basic syntax (using arity types), support and truth semantics, followed by the formalization of a sequent calculus by Litak/Sano whose corresponding paper (Bounded inquistive logics: Sequent calculi and schematic validity) got accepted for [TABLEAUX 2025](https://icetcs.github.io/frocos-itp-tableaux25/tableaux/).

  ### Repository Structure

  - `theories/` provides the main theory, including some preliminary libaries, e.g. `SetoidLib.v`, `ListLib.v`
    * `theories/FO` focuses on inquisitive first-order logic.
  - `instances/` provides some concrete of type classes (e.g. signatures).
  - `examples/` demonstrates some ongoing examples.

  ### Contributing

  You can find information on how to contribute in the [CONTRIBUTING.md](.github/CONTRIBUTING.md) file.

#index_documentation:

coqdoc_index: ./html/toc.html

opam-file-maintainer: ole.elliger@fau.de
#opam-file-version:

#tested_coq_nix_versions:
#tested_coq_opam_versions:
tested_rocq_opam_versions:
  - version: '9.0'
    #repo: 'rocq/rocq-prover'

#ci_cron_schedule:
#cachix:
#circleci_after_script:
