fullname: Template for Coq-Projects on Github
shortname: comoproj
branch: main
organization: motrellin

action: true
action_appendix: |2-
            before_install: |-
              startGroup "Print opam config"
                opam config list; opam repo list; opam list
              endGroup

              startGroup "Build _CoqProject"
                sudo chown -R coq:coq .
                make _CoqProject
              endGroup
            after_script: |-
              make coqdoc
              mkdir public
              cp -r html public/docs
              cp resources/index.md public/index.md
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            path: public
        - name: Revert Coq user permissions
          # to avoid a warning at cleanup time
          if: ${{ always() }}
          run: sudo chown -R 1001:116 .
    deploy:
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: build
      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: html-output
            path: ./out

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./out
            publish_branch: gh-pages
            enable_jekyll: true

community: false
coqdoc: true
submodule: true #At least for coqdocjs
synopsis: A dummy template for Github Coq-Projects
description: |
  No special package. Just used to illustrate a possible template for 
  Github Coq-Projects.

#chat:

authors:
  - name: Max Ole Elliger
    initial: true
    email: ole.elliger@fau.de
maintainers:
  - name: Max Ole Elliger
    nickname: motrellin

license:
  fullname: GNU General Public License v3.0 or later
  identifier: GPL-3.0-or-later

supported_coq_versions:
  text: Developed for 8.19.0
  opam: '{ "8.19" }'

#namespace: CoMoTemplTest

dependencies:
  - description: Coq Equations
    opam:
      name: coq-equations

namespace: CoMoProj

make_target: all

documentation: |-
  ## Documentation

  This project contains a template for Github Coq-Projects. It aims to combine
  several helpful approaches:
  - [Auto-Generating _CoqProject](https://gitlab.cs.fau.de/oc59yqul/template-coq)
  - [Generic repository infrastructure](https://github.com/coq-community/templates)
  - [CoqdocJS](https://github.com/coq-community/coqdocjs)

#index_documentation:

coqdoc_index: ./docs/toc.html

opam-file-maintainer: ole.elliger@fau.de

tested_coq_opam_versions:
  - version: '8.19'
